# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
# list any PHP version you want to test against
php:
  - 5.5

install:
  - composer install

script: 
  - php tests/native.php